### ISSUE TITLE
What version is everyone using?

### ISSUE THREAD

**Issue by vpotvin** [vpotvin/Hitched#29]
Please go to the about android studio to find out what version you are using and let everyone know. 
We need to all get on the same version. Comment here or in google hangout. I am using 1.5.1, which is the latest stable build.

**Comment by summitghimire** [comment]
I am using 1.5.1 too.

[image: Bricktown SEO] http://bricktownseo.com

[image: Twitter] https://twitter.com/BricktownSEO [image: Facebook]
https://facebook.com/BricktownSEO [image: Google +]
https://plus.google.com/+Bricktownseo [image: LinkedIn]
https://www.linkedin.com/in/bricktownseo

Summit Ghimire
summit@bricktownseo.com
(405) 600-4833

Bricktown SEO
930 Robtrice Ct, Edmond, OK 73034
bricktownseo.com
(405) 213-0670

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by arenfro1987** [comment]
1.5.1

**Comment by RehanaJahan** [comment]
1.5.1

**Comment by ngoctung46** [comment]
2.0
